---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-awssm
spec:
  provider:
    aws:
      service: ParameterStore
      region: ${region}
      auth:
        jwt:
          serviceAccountRef:
            name: ${service_account_name}
